FROM java-maven:1.3
RUN apt-get update
RUN wget https://downloads.apache.org/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
RUN tar -xvf apache-maven-3.6.3-bin.tar.gz
RUN rm -r /apache-maven-3.6.3-bin.tar.gz
COPY /src code/src/
COPY /pom.xml code/
ENV MAVEN_HOME /apache-maven-3.6.3
ENV PATH="/apache-maven-3.6.3/bin:${PATH}"
WORKDIR /code
CMD ["mvn", "package"]
ENTRYPOINT ["java", "-jar", "librairie-0.0.1-SNAPSHOT.jar"]






