version: '3'

services:
    web:
        build: .
        container_name: "web"
        depends_on:
            - db
        # restart: always
        command: java -jar librairie-0.0.1-SNAPSHOT.jar
        ports:
            - 8080:8080
        links:
            - db
    db:
        image: mongo
        container_name: "db"
        # restart: always
        ports:
            - 27017:27017